import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Providers from "@/shared/Providers";

const cairo = Cairo({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        suppressHydrationWarning
        className={`${cairo.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
